### ISSUE TITLE
Circular dependencies in a pipeline do not error

### ISSUE THREAD

**Issue by TylerAldrich** [architect-team/arcctl#100]
If a pipeline is trying to apply to a graph with a circular dependency, at some point `getNextStep` will return nothing and the pipeline will finish without errors but with resources still in the pending state (because they were part of the cycle somewhere).

This was happening when I accidentally created a cycle via a datacenter hook:
```
 hooks:
    - when:
        type: ingressRule
      resources:
        dnsRecord:
          type: dnsRecord
          account: ${{ variables.gcpAccount }}
          dnsZone: ${{ environment.resources.zone.id }}
          subdomain: ${{ this.inputs.subdomain }}
          recordType: A
          content: ${{ this.outputs.loadBalancerHostname }}
      dnsZone: ${{ variables.dnsZone }}
      # This uri setting introduces the cycle - the dnsRecord depends on the ingressRule, but now the ingressRule also depends on the dnsRecord!!
      url: ${{ this.resources.dnsRecord.name }}
      namespace: ${{ variables.region }}
```

To fix this, an error should be raised when a cycle is detected during pipeline planning so it fails before starting to modify any resources and potentially leave things in a weird state.
