### ISSUE TITLE
Components pointing to a non-existant resource fails pipeline silently

### ISSUE THREAD

**Issue by TylerAldrich** [architect-team/arcctl#101]
This can be reproduced with the following:

```yml
version: v2

deployments:
  mailslurper:
    image: docker.io/tyleraldrich/mailslurper:latest
    command:
      - sh
      - -c
      - |
        apk update
        apk add wget
        wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        mv jq-linux64 /usr/local/bin/jq
        chmod +x /usr/local/bin/jq
        tmpfile=$(mktemp)
        jq '.wwwPublicURL="${{ ingresses.mailslurper.url }}" | .servicePublicURL="${{ ingresses.mailslurper-api.url }}"' config.json > "$tmpfile"
        mv "$tmpfile" config.json
        ./mailslurper
 
services:
  mailslurper:
    deployment: mailslurper
    port: 8080
  # mailslurper-api:
  #  deployment: mailslurper
  #  port: 8085

ingresses:
  mailslurper:
    service: mailslurper
  # mailslurper-api:
  #  service: mailslurper-api
```

Using this component yaml, which has commented out `services.mailslurper-api` and `ingresses.mailslurper-api`, but has a command that still references `${{ ingresses.mailslurper-api.url }}`, you can deploy this pipeline without errors but the pipeline will finish (allegedly successfully) without applying all the steps.

It eventually reaches a point where it needs the `ingresses.mailslurper-api` to finish before proceeding, but that doesn't exist, so `getNextStep` returns nothing and the pipeline "succeeds". Instead, the pipeline should fail because a reference to a resource that doesn't exist in the graph is present.
