### ISSUE TITLE
Environment Resources and Datacenter Resources can collide

### ISSUE THREAD

**Issue by mueschm** [architect-team/arcctl#116]
**Describe the bug**
If you have an environment resource and a datacenter resource with the same name, only one will be shown by the graph.

**To Reproduce**
```
secrets:
  account: s3
  namespace: arcctl-backend

resources:
  vpc:
    type: vpc
    name: arcctl-datacenter
    account: do
    region: nyc3
  cluster:
    type: kubernetesCluster
    name: arcctl-datacenter
    kubernetesVersion: 1.26.5-do.0
    account: do
    region: nyc3
    vpc: ${{ resources.vpc.id }}
    nodePools:
      - name: pool1
        count: 3
        nodeSize: s-1vcpu-2gb
  namespace:
    type: namespace
    account: ${{ accounts.cluster.id }}
    name: arcctl
  nginx-ingress-controller:
    type: helmChart
    name: ingress-nginx
    account: ${{ accounts.cluster.id }}
    namespace: ${{ resources.namespace.id }}
    repository: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx

accounts:
  cluster:
    name: do-personal-cluster
    provider: kubernetes
    credentials:
      configPath: ${{ resources.cluster.configPath }}

environment:
  resources:
    env-namespace:
      type: namespace
      account: ${{ accounts.cluster.id }}
      name: ${{ environment.name }}

  hooks:
    - when:
        type: secret
      account: secrets
    - when:
        type: databaseSchema
        databaseType: postgres
      resources:
        db:
          type: database
          account: do
          name: ${{ this.id }}
          databaseVersion: ${{ this.inputs.databaseVersion }}
          databaseSize: db-s-1vcpu-1gb
          databaseType: ${{ this.inputs.databaseType }}
          vpc: ${{ resources.vpc.id }}
          region: nyc3
      account: do
      database: ${{ this.resources.db.id }}
    - when:
        type: ingressRule
      resources:
        dnsRecord:
          type: dnsRecord
          account: do
          dnsZone: muesch.me
          subdomain: ${{ this.inputs.subdomain }}
          recordType: A
          content: ${{ this.outputs.loadBalancerHostname }}
      registry: nginx
      namespace: ${{ environment.resources.env-namespace.id }}
      dnsZone: muesch.me
    - account: ${{ accounts.cluster.id }}
      namespace: ${{ environment.resources.env-namespace.id }}
```
Then run
```
arcctl apply dc dopreview ./datacenter.yml --auto-approve
arcctl apply env -d dopreview test1
```
You will see only 1 namespace appears in the list.
Now if you change the name of one of them, they both appear.

**Expected behavior**
There should be no collision between the two resource types.
