### ISSUE TITLE
Allow datacenters to use the state backend as a secret store

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#124]
**Is your feature request related to a problem? Please describe.**

Right now, our example local datacenter, `./__tests__/datacenters/local.yml`, requires the user to provide an account that is to be used to store secrets for the datacenter. This can be a confusing first-touch experience.

**Describe the solution you'd like**

It would be great if datacenters could be designed to automatically utilize the CLIs `state.backend` to store secrets since it is, after all, an account that can store secrets. 

```yml
# example datacenter file

environment:
  hooks:
    - when:
        type: secret
      account: ${{ system.backend.account }}
```
