### ISSUE TITLE
Inject datacenter name into datacenter templates

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#134]
**Is your feature request related to a problem? Please describe.**

When testing or distributing datacenter files, the datacenter-level resources often include hardcoded names unless a variable is defined. In most cases I simply want to use the datacenter name for prefixes or suffixes rather than requiring a variable input.

**Describe the solution you'd like**

I'd like to be able to inject the datacenter name into my config much like I can for the environment name:

```yaml
resources:
  vpc:
    type: vpc
    account: my-account
    name: ${{ datacenter.name }}-vpc
```
