### ISSUE TITLE
Force developers to specify ingress rules in specific datacenters

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#139]
**Is your feature request related to a problem? Please describe.**

Right now arcctl creates randomized subdomains for ingress rules whenever subdomains aren't specified explicitly. However, this kind of magic isn't desirable for production. Operators don't want developers to be able to "accidentally" expose URLs without explicit understanding that they're doing so.

**Describe the solution you'd like**

Unsure of what implementation would look like, but we want the enforcement logic to live inside the datacenter. Maybe a function injection for randomizedSlugs?

```yml
environment:
  hooks:
    - when:
        type: ingressRule
      subdomain: ${{ randomSlug(this.id) }}
```
