### ISSUE TITLE
Make "certificate" resource type

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#141]
**Is your feature request related to a problem? Please describe.**

There are a few use cases where we'd want operators to be able to configure where the certificates come from for ingress rules: 1) origin certs for external firewalls, and 2) using custom providers for certificate issuance and management (e.g. digicert, etc). 

**Describe the solution you'd like**

In order to make this possible, I'd like for there to be a "certificate" resource type that different providers can implement, and I'd also like the ingressRule resource to take in certificate data as external input. Then operators could configure their datacenters to load up the certificate data in many different ways:

```yml
# example datacenter
resources:
  origin-cert:
    type: certificate
    account: cloudflare
    # ...

environment:
  hooks:
    - when:
        type: ingressRule
      certificate:
        ca: ${{ resources.origin-cert.ca }}
        cert: ${{ resources.origin-cert.cert }}
        # ...
```
