### ISSUE TITLE
Add support for declared inputs/secrets

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#16]
The Component framework currently supports the concept of "secrets" which are effectively input values for the component that can be declared as part of the environment configuration. This is perfect for API keys or credentials for external systems.

We need to re-add support for this kind of "secret" in our system. We should create a `secret` resource type and include the relevant nodes in our resource graph. This will allow these input values to be stored how the operations team prefers in their datacenter and mounted to applications using our normal workflow behavior.

## How components declare secrets

Declarative secrets inside components are basically "inputs". In fact, we may change the name of them at a later date. Secrets can have default values and descriptions so that those who deploy it know what values to fill it with. 

Each "secret" inside a component should be transformed into a `secret` resource in our application graphs, and every time an application tries to fill part of its configuration (like the service below) from the secret we should be creating an "edge" in our graph. 

```yml
secrets:
  STRIPE_API_KEY:
    description: stripe API key
    default: tesfsdfs

services:
  api:
    environment:
      STRIPE_KEY: ${{ secrets.STRIPE_API_KEY }}
```

## How environments populate secrets

Secrets are meant to be populated explicitly, and the point of them is that their values will differ in different environments. We'll add helper methods later, but at its core we should be able to assign secret values inside the environment.yml file:

```yml
locals:
  stripe_key: value

components:
  architect/auth:
    source: architect/auth:latest

    secrets:
      STRIPE_API_KEY: ${{ locals.stripe_key }}
```

As you can see, we also are including a "locals" field to help with filling repeat values. Usage of locals should not be required and should not create duplicative resources in the application graph, but should instead fill the values of existing resources.
