### ISSUE TITLE
Leverage the "secret" resource type rules in datacenters to store state

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#17]
_Blocked by #16_

Right now, datacenters have a first-class understanding of terraform state. They skip over the resources/providers abstraction we've created to mirror terraforms concept of "backends" for state storage. This introduces additional complexity into the anatomy of datacenters.

Instead of treating "state" as a different entity, it'd be great to re-use the work to store "secrets" to store state and sensitive output values instead. Instead of configuring "backends" in our terraform jobs (which doesn't work for non-terraform services), we'd be able to store state files or other output values directly inside declared "secrets".

These can't just be nodes in our graph unfortunately because every node will need the ability to store its output values and state somewhere. We'll still need some top-level declaration of stuff in the datacenter for this to work:

```yml
# datacenter schema

secrets:
  provider: vault
  namespace: optional-namespace

resources:
  vpc:
    type: vpc
    # ...

hooks:
  - when:
      type: vpc
     # ...
```
