### ISSUE TITLE
Add “variables” to datacenters

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#36]
Datacenters are supposed to be re-usable and sharable templates that can be used by multiple different orgs and team. Ideally, you’d be able to select different templates from a drop-down or UI.

However, there are a few fields inside the templates that will always be unique to the user like the name of their “account” that brokers access to the required cloud providers. It may also include things like log level, and other interesting globals.

In order to make these templates easier to share, we want to introduce the concept of variables into the data center schema. Declaring a variable would allow our CLI to prompt for the input values whenever you want to create or update a datacenter and apply those values to the template.

## Example

```yaml
variables:
  doAccount:
    description: name of your registered DigitalOcean account.
    required: true
    type: arcctlAccount
    provider: digitalocean
  region:
    type: region
    description: Region to put resources in
    account: ${{ variables.account }}

resources:
  vpc:
    type: vpc
    name: my-vpc
    account: ${{ variables.doAccount }}
    region: ${{ variables.region }}
```

The above example would first prompt for your digital ocean account. Since we specified the “provider” field, we should show a list of all arcctlAccounts matching the digitalocean provider. We should be able to specify types as arcctl resources and use the fields as list() filters.

The second prompt is for the region. Notice how it points to the other variable. That means we need to prompt for the other variable first and then use the result to filter options for the second.

You can also do basic types like string, number, Boolean as well.
