### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#5]
Database migrations are an important features allowing applications to declare the table structure they expect a database to have before they can start writing content to it. Applications _can_ execute these migrations at startup, but this can be risky for large scale environments with multiple replicas. Each may try to run migrations which can create collisions, race conditions, and otherwise ugly behavior.

In this ticket, we'll introduce the `migrate` field to the databases schema that will tell architect to run the migrate task after the database is available and before other applications can connect to it. This field will support all the same values as "cronjobs" minus the "schedule" field.

```yml
databases:
  main:
    type: postgres:13
    migrate:
      image: my-docker-image:latest
      command: npm run migrate
      environment:
        DB_DSN: ${{ databases.main.url }}
```
