### ISSUE TITLE
Allow components to receive values from upstream components

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#59]
The primary use case for components being aware of anything to do with their upstream consumers is security (e.g. allow lists / whitelisting). I'm currently working with [Ory Kratos](https://github.com/ory/kratos) which requires that the allowed "return_to" addresses from its auth redirect flow be registered with the kratos instance. That can only be done dynamically by detecting the URLs of consumers.

## `merge` field in secrets

```yml
# dependency
secrets:
  whitelisted_return_to_urls:
    merge: true
    description: Array of URLs provided by upstream components

deployments:
  kratos:
    environment:
      RETURN_TO_URLS: ${{ secrets.whitelisted_return_to_urls }}

---
# upstream 1

dependencies:
  kratos:
    source: architect/kratos
    secrets:
      whitelisted_return_to_urls:
        - ${{ ingresses.main.url }}

ingresses:
  main:
    service: main

---
# upstream 2

dependencies:
  kratos:
    source: architect/kratos
    secrets:
      whitelisted_return_to_urls:
        - ${{ ingresses.main.url }}

ingresses:
  main:
    service: main

---
# environments

components:
  architect/kratos:
    secrets:
      whitelisted_return_to_urls:
        - http://legacy-host.com
```
