### ISSUE TITLE
Database seeding

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#6]
Database seeding is an important feature for on-demand environments to allow those environments to be loaded with data when booting up from scratch. 

```yml
# component schema
databases:
  main:
    type: postgres:13
    seed:
      image: my-image:latest
      command: npm run seed
      environment:
        DB_ADDR: ${{ databases.main.url }}
```

Not all environments will want to run seed scripts. For this reason, you'll have to enable seed scripts in your environment configuration:

```yml
# environment schema

flags:
  database_seeding: true

components:
  architect/cloud:
    source: architect/cloud:latest

# ...
```
