### ISSUE TITLE
Resource "strategies"

### ISSUE THREAD

**Issue by davidthor** [architect-team/arcctl#7]
Sometimes providers have multiple methods by which they can fulfill resource requests. For example, AWS could power "deployments" with both ECS services, lambda functions, and a few other solutions. In order to facilitate this, we'll want to allow resources to define optional "strategies" that can be used for each resource type.

In order to accomplish this, we'll be modifying the `ResourceService` class to include a `strategies()` method that will return an array of strings that represent supported strategies for the resource type by the associated provider. The response should be async so that the method can optionally query the provider to determine if the credentials provided have access to each strategy type. 

## Example

```yaml
type: deployment
provider: my-aws-account
image: my-image:latest
strategy: ecs-fargate
```
